### ISSUE TITLE
有2个小问题，不知是我操作有误还是bug？

### ISSUE THREAD

**Issue by ananix** [perfree/jpress-perfree-simple#6]
**1. md文档格式不能正常展示**
比如我用的加粗斜体，在模版里并没展示出相应的格式，
这是后头文章：
![image](https://user-images.githubusercontent.com/17675071/57580436-29894580-74dc-11e9-8370-fdf64eb8a3ae.png)
这是模版页面：
![image](https://user-images.githubusercontent.com/17675071/57580460-70773b00-74dc-11e9-989c-6afeb6324d8d.png)
请注意查看【*** --模糊查询 LIKE***】这部分内容，当然这只是举例，不光加粗斜体，像引用、标题等有时也会有同样的问题，在后台md写得很好看的文章，在模版里展示就不是那么美观了
**2.更新的赞赏功能图片太大问题**
看到模版更新了赞赏功能后马上就下在安装试了一下：下载zip安装，配置模版打开赞赏功能，手机保存微信，支付宝收款码图片，上传图片到模版，保存模版设置。
打开文章查看，发现：
![image](https://user-images.githubusercontent.com/17675071/57580574-111a2a80-74de-11e9-8672-faa303960725.png)

**Comment by perfree** [comment]
1.目前加粗斜体暂不支持，下版会修复增加，md渲染的样式可以参考http://www.jpress.yinpengfei.com/article/5

**Comment by perfree** [comment]
2.更新完模板之后，浏览器会有pjax缓存，需要强制刷新下页面shift+f5
